CREATE TABLE IF NOT EXISTS T_ORDER (
    ORDER_ID            BIGINT          NOT NULL AUTO_INCREMENT
  , COMPANY_CODE        VARCHAR  ( 4 )  NOT NULL
  , ORDER_INFOMATION    TEXT            NOT NULL
  , CREATE_USER_ID      VARCHAR  ( 8 )  NOT NULL
  , CREATE_DATE_TIME    DATETIME ( 6 )  NOT NULL
  , UPDATE_USER_ID      VARCHAR  ( 8 )
  , UPDATE_DATE_TIME    DATETIME ( 6 )
  , VERSION_NUMBER      SMALLINT        NOT NULL
  , LOGICAL_DELETE_FLAG BOOLEAN         NOT NULL     
  , PRIMARY KEY ( ORDER_ID )
)
;

CREATE INDEX IX1_ORDER ON T_ORDER( COMPANY_CODE );
